# ====== TU INFORMACIÓN ======
title: Santiago Cervantes Strevel
description: Pagina Web Pensamiento de Ingeniería
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

# Nombre de tu repositorio
baseurl: "/Documentacion"
url: "https://santidwago-pixel.github.io"

# Colores: edita _sass/color_schemes/custom.scss
color_scheme: custom

# Logo opcional (sube assets/images/logo.png y quita el #)
# logo: "/assets/images/logo.png"

search_enabled: true

aux_links:
  "Mi GitHub":
    - "https://github.com/Santidwago-pixel/Documentacion"

footer_content: "© 2026 Santiago Cervantes Strevel · Ingenieria Mecatronica · Universidad Iberoamericana"
